name: Build & Release PowerResizer64

on:
  push:
    tags: [ 'v*' ]         # build whenever you push a tag like v0.96
  workflow_dispatch:       # …or let you run it manually

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Install MSVC / Windows SDK build tools
      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2   # sets up VS 2022 Build Tools

      - name: Build Release x64
        run: msbuild PowerResizer.sln /p:Configuration=Release /p:Platform=x64 /m

      # Upload compiled EXE & DLL as artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PowerResizer64
          path: |
            bin\x64\Release\PowerResizer64.exe
            bin\x64\Release\PowerResizer64.dll

      # (Optional) attach them to a GitHub Release when you push a tag
      - name: Draft Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          files: |
            bin\x64\Release\PowerResizer64.exe
            bin\x64\Release\PowerResizer64.dll
